basePath: /
consumes:
- application/json
host: some-url.com
info:
  description: Documentation of our awesome API.
  title: apptest.
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
